# -*- coding: utf-8 -*-
"""[REVISED] FINAL CAPSTONE PROJECT - STT & analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6SNAEUCep6rR4DWpEuRGeiEVHrWmrBu

# Video to Text

## Import
"""

!pip install openai-whisper torch ffmpeg-python
!pip install -U sentence-transformers jiwer
import whisper
import ffmpeg
from sentence_transformers import SentenceTransformer, util
!pip install -U sentence-transformers

# --- Imports & embedder ---
from sentence_transformers import SentenceTransformer, util

# Model ringan dan akurat untuk semantic similarity
EMBEDDER_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"

try:
    embedder
except NameError:
    embedder = SentenceTransformer(EMBEDDER_MODEL_ID)

"""## Processing"""

import ffmpeg
import whisper

def process_file(input_file, output_index):
    output_file = f"audio_clean_{output_index}.wav"

    # Extract audio
    ffmpeg.input(input_file).output(output_file, ac=1, ar=16000).run(overwrite_output=True)

    # Load Whisper
    model = whisper.load_model("medium")
    audio = whisper.load_audio(output_file)
    result = model.transcribe(
        audio=output_file,
        language="en",
        word_timestamps=True
    )

    pause_word_gap = 0.5
    pause_segment_gap = 0.5

    segments = []
    current_segment = []
    seg_start = None
    prev_end = None

    def to_timestamp(sec):
        m = int(sec // 60)
        s = int(sec % 60)
        return f"{m:02d}:{s:02d}"

    # Segment
    for seg in result["segments"]:
        words = seg.get("words", [])
        if not words:
            continue

        if prev_end is not None and words[0]["start"] - prev_end > pause_segment_gap:
            if current_segment:
                seg_end = prev_end
                text = " ".join(current_segment).strip()
                segments.append((seg_start, seg_end, text))
                current_segment = []
                seg_start = None

        for i, w in enumerate(words):
            if seg_start is None:
                seg_start = w["start"]

            current_segment.append(w["word"])

            if i < len(words) - 1:
                gap = words[i + 1]["start"] - w["end"]
                if gap > pause_word_gap:
                    seg_end = w["end"]
                    text = " ".join(current_segment).strip()
                    segments.append((seg_start, seg_end, text))
                    current_segment = []
                    seg_start = words[i + 1]["start"]

        prev_end = words[-1]["end"]

    if current_segment:
        seg_end = prev_end
        text = " ".join(current_segment).strip()
        segments.append((seg_start, seg_end, text))

    # jeda
    pauses = []
    for i in range(1, len(segments)):
        pause_dur = segments[i][0] - segments[i - 1][1]
        if pause_dur > 0:
            pauses.append(pause_dur)

    total_silence = len(pauses)


    try:
        info = ffmpeg.probe(input_file)
        duration_sec = float(info["format"]["duration"])
    except:
        duration_sec = len(audio) / 16000

    # Output Text
    final_text = ""
    for idx, (start, end, text) in enumerate(segments):
        final_text += f"[{to_timestamp(start)} - {to_timestamp(end)}] {text}\n"
        if idx < len(pauses):
            final_text += f"[PAUSE {pauses[idx]:.2f}s]\n"

    final_text += f"\nTotal jeda terdeteksi: {total_silence}\n"
    final_text += f"Durasi total video: {duration_sec:.2f} detik\n"

    out_name = f"hasil_segment_timestamp_sensitif_{output_index}.txt"
    with open(out_name, "w", encoding="utf-8") as f:
        f.write(final_text)

    print(f"Konversi : {input_file} → {out_name}")


    return {
        "file": input_file,
        "segments": segments,
        "pauses": pauses,
        "total_silence": total_silence,
        "duration": duration_sec,
        "text_output": final_text,
        "full_transcript": result.get("text", final_text)  # fallback
    }




input_files = [
    "/content/interview_question_1 (3).webm",
    "/content/interview_question_2.webm",
    "/content/interview_question_3 (1).webm",
    "/content/interview_question_4 (3).webm",
    "/content/interview_question_5 (2).webm",
]

all_results = []

for idx, file in enumerate(input_files, start=1):
    r = process_file(file, idx)
    all_results.append(r)

print("\n=== OUTPUT SUMMARY ===\n")

for i, res in enumerate(all_results, start=1):
    print(f"Video {i}: {res['file']}")
    print(f"  Segments       : {len(res['segments'])}")
    print(f"  Pauses detected: {res['total_silence']}")
    print(f"  Duration       : {res['duration']:.2f} sec\n")

all_text = ""


for i, res in enumerate(all_results, start=1):
    all_text += f"\n\n=== TEXT VIDEO {i} ===\n"
    all_text += res["text_output"]

print(all_text)

"""INPUT PERTANYAAN HR & RUBRIC"""

# =====================================================
# Setup Pertanyaan (HR Input) - AUTO JUMLAH VIDEO
# =====================================================

NUM_VIDEOS = len(all_results)

QUESTION_TEXTS = []
RUBRIC_TEXTS = []

print(f"\nTerdeteksi {NUM_VIDEOS} video. Silakan input pertanyaan & rubric setiap video.\n")

for i in range(1, NUM_VIDEOS + 1):
    print(f"\n=== INPUT UNTUK PERTANYAAN VIDEO #{i} ===")
    q = input(f"Masukkan pertanyaan HR untuk video #{i}: ")
    r = input(f"Masukkan rubric score 4 (detail) untuk video #{i}: ")
    QUESTION_TEXTS.append(q)
    RUBRIC_TEXTS.append(r)

#question = "Can you share any specific challenges you faced while working on certification and how you overcame them?"

#rubric_4 = """
#The candidate provides a comprehensive and very clear response.
#- Gives a detailed description of specific challenges encountered during the certification.
#- Explains clearly how each challenge was overcome, including concrete and practical actions taken.
#- Demonstrates strong understanding of technical aspects and problem-solving skills related to the certification process.
#- Provides structured, well-organized answers with depth and reflection on the learning process.
#- Offers insights that show real experience, not generic or surface-level explanations.
#"""

"""# Text Extraction & Modelling

## Install Dependencies
"""

import os
from dotenv import load_dotenv
from openai import OpenAI
import numpy as np
from numpy.linalg import norm

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
base_url = os.getenv("OPENAI_BASE_URL")
client = OpenAI(api_key=api_key, base_url=base_url) if api_key and base_url else None

MODEL = "gpt-4o-mini"
EMBED_MODEL = "text-embedding-3-small"

"""## Import & Load Models
- Gemma-2B-IT → untuk generate keyword otomatis
- SentenceTransformer → untuk semantic scoring
"""

def call_llm(prompt, max_tokens=500, temperature=0.2):
    if client is None:
        raise RuntimeError(
            "OPENAI_API_KEY and OPENAI_BASE_URL must be configured in the "
            "environment or in backend/.env before running the app."
        )

    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens,
        temperature=temperature
    )
    return response.choices[0].message.content

"""## Keyword Generator LLM (Level 2 Automation)

## Generate Keyword
"""

import json
import re

def generate_keywords_from_llm(question, rubric_desc_4):
    prompt = f"""
You are an HR expert. Generate structured keyword sets based on:

INTERVIEW QUESTION:
{question}

PERFECT ANSWER (Score 4):
{rubric_desc_4}

Respond ONLY in this JSON format:

{{
  "specific_keywords": [],
  "action_keywords": [],
  "conceptual_keywords": [],
  "general_keywords": [],
  "semantic_reference": []
}}
"""

    output = call_llm(prompt)

    # extract JSON
    json_start = output.find("{")
    json_end = output.rfind("}") + 1
    json_str = output[json_start:json_end]

    # cleanup
    json_str = json_str.replace("\n", " ").replace("\t", " ")
    json_str = re.sub(r",\s*}", "}", json_str)
    json_str = re.sub(r",\s*]", "]", json_str)

    return json.loads(json_str)

# =====================================================
# Generate Keyword Bank berdasarkan tiap pertanyaan
# =====================================================

QUESTION_KEYWORD_BANK = {}

for i in range(NUM_VIDEOS):
    q_label = f"q{i+1}"
    QUESTION_KEYWORD_BANK[q_label] = generate_keywords_from_llm(
        QUESTION_TEXTS[i],
        RUBRIC_TEXTS[i]
    )

print("\n=== SEMUA KEYWORD BANK BERHASIL DIBUAT ===")
for k, v in QUESTION_KEYWORD_BANK.items():
    print(f"{k}: {len(v['specific_keywords'])} specific keywords")

"""simpan variable yang dibutuhkan"""

full_transcript = res["full_transcript"]
segments = res["segments"]
pauses = res["pauses"]
duration_sec = res["duration"]

if not full_transcript:
    full_transcript = " ".join(seg[2] for seg in segments).strip()

total_silence = sum(pauses)
total_duration = duration_sec
gaps = pauses

"""## Raw Cleaning & Raw Analysis (Fluency + AI Suspect)"""

def clean_text_raw(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'\(.*?\)', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

"""Fluency"""

def analyze_fluency_from_silence(total_silence, total_duration, gaps):
    silence_ratio = total_silence / total_duration
    avg_gap = total_silence / len(gaps) if len(gaps) > 0 else 0
    gap_freq = len(gaps) / total_duration

    score = 4

    # Silence ratio (persentase jeda)
    if silence_ratio > 0.25:
        score -= 3
    elif silence_ratio > 0.15:
        score -= 2
    elif silence_ratio > 0.08:
        score -= 1

    # Average gap length
    if avg_gap > 2.0:
        score -= 2
    elif avg_gap > 1.2:
        score -= 1

    # Gap frequency
    if gap_freq > (1/4):  # lebih dari 1 gap setiap 4 detik
        score -= 1

    score = max(1, min(score, 4))

    return {
        "fluency_score": score,
        "silence_ratio": silence_ratio,
        "avg_gap": avg_gap,
        "gap_frequency": gap_freq
    }

"""## AI Detector

SILENCE-BASED AI DETECTOR
"""

def analyze_ai_suspect_from_silence(total_silence, total_duration, gaps):
    if total_duration == 0:
        return 0

    silence_ratio = total_silence / total_duration
    avg_gap = sum(gaps) / len(gaps) if gaps else 0
    gap_variance = (max(gaps) - min(gaps)) if len(gaps) > 1 else 0

    score = 0

    # 1. AI hampir tanpa jeda
    if silence_ratio < 0.02:
        score += 2

    # 2. Jeda pendek → AI
    if avg_gap < 0.40:
        score += 1

    # 3. Variasi jeda stabil
    if gap_variance < 0.3:
        score += 1

    # 4. Jeda seragam → AI
    if len(gaps) > 0 and all(0.20 < g < 0.55 for g in gaps):
        score += 1

    return min(score, 4)

"""EMBEDDING-BASED AI STYLE DETECTOR

3.1 Utility cosine
"""

def cosine_similarity(a, b):
    return np.dot(a, b) / (norm(a) * norm(b))

"""Build AI-style centroid"""

def build_ai_style_embedding(prompts):
    vectors = []
    for p in prompts:
        resp = client.embeddings.create(
            model=EMBED_MODEL,
            input=p
        )
        vectors.append(np.array(resp.data[0].embedding))
    return np.mean(vectors, axis=0)

"""3.3 AI-style prompts"""

AI_STYLE_PROMPTS = [
    "I believe my greatest strength is my ability to stay focused under pressure.",
    "I am highly motivated and always eager to improve myself.",
    "I work well in teams and enjoy collaborative environments.",
    "I consistently strive for professionalism and clear communication.",
]

"""3.4 Generate centroid (jalankan saat server startup)"""

AI_CENTROID = build_ai_style_embedding(AI_STYLE_PROMPTS)

"""3.5 Detector dari embedding similarity"""

def analyze_ai_suspect_from_embedding(text, ai_centroid):
    resp = client.embeddings.create(
        model=EMBED_MODEL,
        input=text
    )
    emb = np.array(resp.data[0].embedding)

    sim = cosine_similarity(emb, ai_centroid)

    # Skor AI-likeness dari similarity
    if sim > 0.90:
        score = 3
    elif sim > 0.87:
        score = 2
    elif sim > 0.83:
        score = 1
    else:
        score = 0

    return {
        "similarity": sim,
        "embedding_score": score
    }

"""FINAL AI-COMBINED DETECTOR"""

def analyze_ai_combined(text, total_silence, total_duration, gaps, ai_centroid):
    silence_score = analyze_ai_suspect_from_silence(total_silence, total_duration, gaps)
    emb_data = analyze_ai_suspect_from_embedding(text, ai_centroid)

    embedding_score = emb_data["embedding_score"]
    total_score = silence_score + embedding_score

    if total_score >= 6:
        label = "Highly AI-like"
    elif total_score >= 4:
        label = "Likely AI-like"
    elif total_score >= 2:
        label = "Somewhat AI-like"
    else:
        label = "Likely Human"

    return {
        "silence_score": silence_score,
        "embedding_similarity": emb_data["similarity"],
        "embedding_score": embedding_score,
        "ai_score_total": total_score,
        "ai_label": label
    }

"""## Clean Text for Semantic Analysis"""

def clean_text_semantic(text):
    text = text.lower()
    filler = ["uh", "um", "emm", "hmm", "erm", "you know", "like", "kinda", "sorta"]
    for f in filler:
        text = text.replace(f, "")

    text = re.sub(r'\b(\w+)\s+\1\b', r'\1', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

"""## Semantic Similarity Helper"""

def semantic_sim(a, b):
    emb1 = embedder.encode(a, convert_to_tensor=True, normalize_embeddings=True)
    emb2 = embedder.encode(b, convert_to_tensor=True, normalize_embeddings=True)
    return float(util.cos_sim(emb1, emb2).item())

"""## Rubric Scoring (Auto Keyword-Based)"""

# =====================================================
# Rubric Scoring (Auto Keyword-Based, per-pertanyaan)
# =====================================================

def rubric_scoring(clean, qtype="q1"):
    """
    Scoring jawaban berdasarkan QUESTION_KEYWORD_BANK[qtype]
    qtype contoh: 'q1', 'q2', dst.
    """
    kw = QUESTION_KEYWORD_BANK[qtype]

    specific_hit = any(k.lower() in clean for k in kw["specific_keywords"])
    action_hit   = any(k.lower() in clean for k in kw["action_keywords"])
    concept_hit  = any(k.lower() in clean for k in kw["conceptual_keywords"])
    general_hit  = any(k.lower() in clean for k in kw["general_keywords"])

    semantic_scores = []
    for ref in kw["semantic_reference"]:
        semantic_scores.append(semantic_sim(clean, ref))
    semantic_best = max(semantic_scores) if semantic_scores else 0

    # Scoring rules
    if (specific_hit and action_hit and concept_hit) and semantic_best > 0.60:
        return 4, "Highly detailed answer aligned with expected standards."
    if specific_hit and (action_hit or concept_hit or semantic_best > 0.45):
        return 3, "Specific answer with clear reasoning."
    if general_hit:
        return 2, "General explanation lacking detail."
    if len(clean.split()) < 20:
        return 1, "Minimal or vague response."
    return 1, "Vague response lacking structure."

def rubric_scoring_dynamic(clean_text):
    kw = QUESTION_KEYWORD_BANK["dynamic"]

    specific_hit = any(k.lower() in clean_text for k in kw["specific_keywords"])
    action_hit   = any(k.lower() in clean_text for k in kw["action_keywords"])
    concept_hit  = any(k.lower() in clean_text for k in kw["conceptual_keywords"])
    general_hit  = any(k.lower() in clean_text for k in kw["general_keywords"])

    # semantic scoring
    semantic_scores = []
    for ref in kw["semantic_reference"]:
        semantic_scores.append(semantic_sim(clean_text, ref))

    semantic_best = max(semantic_scores) if semantic_scores else 0

    # Scoring
    if (specific_hit and action_hit and concept_hit) and semantic_best > 0.60:
        return 4, "Strong, detailed, and aligned with rubric expectations."

    if specific_hit and (action_hit or concept_hit or semantic_best > 0.45):
        return 3, "Good structure with decent depth."

    if general_hit:
        return 2, "General answer, lacks specifics."

    return 1, "Vague or insufficient response."

"""## Final Pipeline Integration"""

# =====================================================
# 9. Final Pipeline Integration - evaluate_answer
# =====================================================

def evaluate_answer(
    text,
    total_silence,
    total_duration,
    gaps,
    qtype="q1",              # default q1, nanti diisi q1..qN
    ai_centroid=AI_CENTROID
):
    # 1. Raw cleaning
    raw = clean_text_raw(text)

    # 2. Fluency dari silence
    fluency_data = analyze_fluency_from_silence(total_silence, total_duration, gaps)

    # 3. AI detection (silence only + combined)
    ai_silence_only = analyze_ai_suspect_from_silence(total_silence, total_duration, gaps)
    ai_combined = analyze_ai_combined(raw, total_silence, total_duration, gaps, ai_centroid)

    # 4. Clean for semantic scoring
    clean = clean_text_semantic(raw)

    # 5. Rubric scoring (per-pertanyaan)
    rscore, rreason = rubric_scoring(clean, qtype)

    # 6. Bundle final
    return {
        "raw_text": raw,
        "clean_text": clean,
        "fluency_score": fluency_data["fluency_score"],
        "fluency_meta": fluency_data,
        "ai_suspect_silence_only": ai_silence_only,
        "ai_suspect": ai_combined,
        "rubric_score": rscore,
        "rubric_reason": rreason,
        "final_score": rscore
    }

# =====================================================
# 9b. Evaluasi per video (wrapper)
# =====================================================

def evaluate_video_result(result_dict, q_index):
    """
    q_index = index pertanyaan sesuai nomor video (dimulai dari 1)
    q1 -> video 1, q2 -> video 2, dst.
    """
    q_label = f"q{q_index}"

    text = result_dict["full_transcript"]
    total_silence = result_dict["total_silence"]
    total_duration = result_dict["duration"]
    gaps = result_dict["pauses"]

    evaluation = evaluate_answer(
        text=text,
        total_silence=total_silence,
        total_duration=total_duration,
        gaps=gaps,
        qtype=q_label,
        ai_centroid=AI_CENTROID
    )

    return {
        "file": result_dict["file"],
        "question": QUESTION_TEXTS[q_index - 1],
        "transcript": text,
        "silence": total_silence,
        "duration": total_duration,
        "gaps": gaps,
        "analysis": evaluation
    }


# =====================================================
# ANALISIS PER VIDEO OTOMATIS
# =====================================================

ALL_ANALYSIS_RESULTS = []

for idx, res in enumerate(all_results, start=1):
    print(f"\n=== ANALYSIS FOR VIDEO #{idx} ===")
    eval_result = evaluate_video_result(res, q_index=idx)
    ALL_ANALYSIS_RESULTS.append(eval_result)

"""## Final result"""

# =====================================================
# Final result
# =====================================================

print("\n================ FINAL ANALYSIS SUMMARY ================\n")

for i, item in enumerate(ALL_ANALYSIS_RESULTS, start=1):
    print(f"--- VIDEO {i}: {item['file']} ---")
    print(f"Pertanyaan           : {item['question']}")
    print(f"Final Score          : {item['analysis']['final_score']}")
    print(f"Rubric Reason        : {item['analysis']['rubric_reason']}")
    print(f"Fluency Score        : {item['analysis']['fluency_score']}")
    print(f"AI-Likeness Label    : {item['analysis']['ai_suspect']['ai_label']}")
    print(f"AI Silence Score     : {item['analysis']['ai_suspect_silence_only']}")
    print()

import json
from datetime import datetime

json_output = {
    "generated_at": datetime.now().isoformat(),
    "total_videos": len(ALL_ANALYSIS_RESULTS),
    "videos": []
}

for i, item in enumerate(ALL_ANALYSIS_RESULTS, start=1):

    video_json = {
        "video_id": i,
        "file_path": item["file"],
        "question": item["question"],
        "final_score": item["analysis"]["final_score"],
        "rubric_reason": item["analysis"]["rubric_reason"],
        "fluency_score": item["analysis"]["fluency_score"],
        "ai_likeness_label": item["analysis"]["ai_suspect"]["ai_label"],
        "ai_silence_score": item["analysis"]["ai_suspect_silence_only"],
        "duration_sec": item.get("duration", 0)
    }

    json_output["videos"].append(video_json)

# Pretty printed JSON
print(json.dumps(json_output, indent=4))

# Optional: Save into file
with open("final_analysis_output.json", "w") as f:
    json.dump(json_output, f, indent=4)
